eureka:
  instance:
    hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
server:
    port: 8761
spring:
    application:
        name: discovery-server
    zipkin:
        base-url: http://localhost:9411
logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]"
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    propagation:
      consume: b3
    sampling:
      probability: 1.0
    enabled: true


