eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/



logging:
    #root: INFO
    #org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    #3org.springframework.cloud.gateway: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]"

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
## Product Service Route
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product
        predicates[1]: Path=/api/product

## Order Service Route
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order/**

## Inventory Service Route
      routes[2]:
        id: inventory-service
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventory/**

##

## Discovery Server Route
      routes[3]:
        id: discovery-server
        uri: lb://discovery-server
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
## Discovery Server Static Resources Route
      routes[4]:
        id: discovery-server-static
        uri: lb://discovery-server
        predicates[0]: Path=/eureka/**

## User Service Route
      routes[5]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/user/api/**

## Invoice Service Route
      routes[6]:
        id: invoice-service
        uri: lb://invoice-service
        predicates[0]: Path=/api/invoice/**




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    propagation:
      consume: b3
    sampling:
      probability: 1.0



server:
    port: 8080
